USC-ACTLab/crazyswarm

docs/installation.rst
To clarify things after issue #69: add a warning the installation page that Crazyswarm will not work in WSL.
=> Add warning about running ubuntu in WSL. Related to issue #69

docs/installation.rst
Had 2 unspecified (but very, very common) dependencies. Allows for install on a minimal lubuntu machine.
=> Updated dependency list

conda_env.yaml
Add pyqt to conda_env, which is a dependency for vispy.
=> add pyqt to conda_env

ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyflie.py, ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyflieSim.py, ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyswarm.py, ros_ws/src/crazyswarm/scripts/testYamlString.py
Until now, the set of robots in a pycrazyswarm script is always
determined by ros_ws/src/crazyswarm/launch/crazyflies.yaml. This
couples the result of the script to the state of the executing machine.
If we want to add more automated testing in the future, it should be
possible to write a pycrazyswarm script that runs deterministically
without the cumbersome process of writing .yaml to disk.
=> Option to load crazyflies.yaml from string or alternate path.

ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyflieSim.py
`crazyflieSim.Crazyflie` previously did not have separate concepts of "setpoint" and "state". This made sense when we were only tracking polynomial trajectories or using `cmdFullState`. It became a little awkward when we added `cmdVelocity`. Now, as I am trying to implement onboard collision avoidance for https://github.com/bitcraze/crazyflie-firmware/issues/567, there is no way around separating those two concepts.
Instead of trying to duplicate the firmware's commander, I used the concept of "flight modes" that we both prefer. The state and setpoint are stored as `traj_eval` SWIG objects to make interfacing with other wrapped firmware modules easy.
I have ran all the scripts, everything seems to work in vispy.
I am hoping this can be a way to try ideas for an eventual refactor of the …
=> refactor crazyflieSim

ros_ws/src/crazyswarm/src/crazyswarm_server.cpp
The current code temporarily instantiated Crazyflie objects to call
sysOn. This had two major issues:
1. OnConsole messages received during this period are not logged using
ROS_INFO. This essentially prevents the Crazyswarm from printing
useful start-up sequence information (e.g., failures during sensor
or deck initialization.)
2. This method never worked correctly for more than 5 CFs. Instead, the
recommended use-case always has been to reboot selected CFs using
chooser.py before launching the crazyswarm_server.
Because of 2., the safest (and easiest) way to fix 1. is to remove the
code accordingly.
=> Fix issue where Crazyflie debug output was not fully printed.

ros_ws/src/crazyswarm/src/crazyswarm_server.cpp
When enabled, /cf<id>/pose is published with the internal state estimate
from the on-board EKF. This is useful for on-board state estimators
(flow deck, lighthouse, LPS).
=> Add pose log topic.

.github/workflows/ci-ros.yml, .github/workflows/ci-simonly.yml
Recreate our CI workflows in Github Actions.
As mentioned in #222, Github stopped showing our "green checkmarks" a while back. Even worse, at some point we started getting "unauthenticated packages" errors (like [this](https://travis-ci.org/github/USC-ACTLab/crazyswarm/jobs/708110502)) non-deterministically.
=> Port CI from Travis to Github Actions (#222)

.gitmodules, build.sh
As discussed in https://github.com/USC-ACTLab/crazyswarm/discussions/391. Leaving all the prebuilt binaries for user convenience.
=> remove NRF and radio submodules, don't build fw in build.sh

ros_ws/src/crazyswarm/scripts/pycrazyswarm/genericJoystick.py, ros_ws/src/crazyswarm/scripts/pycrazyswarm/linuxjsdev.py
See the last question in the thread of #399. We assumed that if any joystick devices exist, then one of them has the id `0`. This wasn't true for a user.
=> do not assume that joystick 0 must exist

.gitmodules, build.sh, docs/conf.py, docs/howto/streaming_setpoint.rst, ros_ws/src/crazyswarm/CMakeLists.txt, ros_ws/src/crazyswarm/msg/FullState.msg, ros_ws/src/crazyswarm/msg/GenericLogData.msg, ros_ws/src/crazyswarm/msg/Hover.msg, ros_ws/src/crazyswarm/msg/LogBlock.msg, ros_ws/src/crazyswarm/msg/Position.msg, ros_ws/src/crazyswarm/msg/TrajectoryPolynomialPiece.msg, ros_ws/src/crazyswarm/msg/VelocityWorld.msg, ros_ws/src/crazyswarm/package.xml, ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyflie.py, ros_ws/src/crazyswarm/src/crazyswarm_server.cpp, ros_ws/src/crazyswarm/src/crazyswarm_teleop.cpp, ros_ws/src/crazyswarm/srv/GoTo.srv, ros_ws/src/crazyswarm/srv/Land.srv, ros_ws/src/crazyswarm/srv/NotifySetpointsStop.srv, ros_ws/src/crazyswarm/srv/SetGroupMask.srv, ros_ws/src/crazyswarm/srv/StartTrajectory.srv, ros_ws/src/crazyswarm/srv/Stop.srv, ros_ws/src/crazyswarm/srv/Takeoff.srv, ros_ws/src/crazyswarm/srv/UpdateParams.srv, ros_ws/src/crazyswarm/srv/UploadTrajectory.srv
Crazyflie_ros will be deprecated in favor of the Crazyswarm. In order
to avoid unnecessary deep dependencies, we move all the custom messages
and services directly into the Crazyswarm project.
This change also avoids to have crazyflie_cpp twice. Now, only the one
that comes with crazyflie_tools is used.
=> Remove dependency to crazyflie_ros by adding msg/srv directly here.

ros_ws/src/crazyswarm/scripts/chooser.py
This PR fixes the error that currently occurs when checking the battery status of a non-existent crazyflie with the `chooser.py` script. Instead of printing an exception in the terminal, the chooser now displays `N/A` for all the (checked) crazyflies that are not available.
=> Fixes error when retrieving unavailable CF battery status

ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyflieSim.py, ros_ws/src/crazyswarm/scripts/pycrazyswarm/visualizer/visVispy.py, ros_ws/src/crazyswarm/scripts/test_simOnly.py
Bug #445 was ultimately due to VisPy's decision to use the "DirectX convention" of column-major/right-multiplying model matrices (see http://www.mindcontrol.org/~hplus/graphics/matrix-layout.html, https://github.com/vispy/vispy/issues/507).
Previously we had a `matrix -> Euler angles -> matrix` round trip because `CrazyflieSim` only exposed attitude state via the `rpy()` method, not via matrices. This was obscuring the bug so I added `rot_bodytoworld()` to help debug. Might as well keep it for clarity and efficiency.
=> use matrices instead of rpy in VisVispy

build.sh, ros_ws/src/crazyswarm/CMakeLists.txt
This dependency is required if the srv/msg descriptions are in the same
package, see https://answers.ros.org/question/53265/catkin-messages-and-node-in-same-package/
Fixes issue #461.
=> Add dependency for nodes to messages

ros_ws/src/crazyswarm/launch/hover_swarm.launch, ros_ws/src/crazyswarm/src/crazyswarm_server.cpp
In case the motioncapturetype is set to "none", logging is enabled, and
logging_pose is enabled, the current pose will be still shown in rviz.
This is in particular useful for testing with LightHouse, LPS, or flow
deck.
=> Show current pose of the Crazyflies even if no external mocap is used

ros_ws/src/crazyswarm/launch/hover_swarm.launch
The point cloud log file is rarely used, so there is no reason to fill the user's storage with a potentially large file.
=> do not log point cloud files by default

docs/installation.rst
* SDCC is not required anymore, since we removed the radio-firmware
* ros-[ROS version]-vrpn is not required anymore (VRPN is now a
submodule of libmotioncapture)
* ros-[ROS version]-joy was missing, see issue #353
=> Docs: update dependencies for physical experiments

.github/workflows/ci-ros.yml, docs/Makefile, docs/generate_install_deps_code.py, docs/generated/.gitignore, docs/installation.rst
We maintain lists of Ubuntu (and now Pip) packages for dependencies in two different places: the CI script and the docs. This creates an opportunity for them to diverge (e.g. 2c3e789a637d8c41e1a1906faaae1dd7dce1a6e4 could have also removed `sdcc` from the CI version).
In #342 we considered and rejected the idea of somehow running the CI script on the local machine. It is too complicated.
In #342 we also discussed the idea of moving the dependency install into a shell script. This is reasonable, but I prefer showing the list of installed packages in the docs for transparency.
Therefore, we instead generate the docs from the CI script in this PR.
=> Generate "install dependencies" docs from CI script

docs/configuration.rst, docs/gettingstarted.rst, docs/howto/git_integration.rstinclude, docs/index.rst
In the current documentation it remained unclear that we support LPS,
LightHouse etc. This updates the documentation throughout. The biggest
change is in configuration.rst, which required some re-ordering of
paragraphs.
Addresses issue #108.
=> Docs: Clarify that we support not only mocap for external tracking

.github/workflows/ci-ros.yml, docs/installation.rst, ros_ws/src/crazyswarm/scripts/test_videoOutput.py
* Update test_videoOutput to use the correct Python version
* Add missing information to docs
Fixes issue #496
=> Fix two failing Python Tests on Ubuntu 20.04

docs/configuration.rst, ros_ws/src/crazyswarm/CMakeLists.txt, ros_ws/src/crazyswarm/launch/hover_swarm.launch, ros_ws/src/crazyswarm/launch/mocap_helper.launch, ros_ws/src/crazyswarm/src/crazyswarm_server.cpp, ros_ws/src/crazyswarm/src/mocap_helper.cpp
* This also uses the EXCLUDE_FROM_ALL flag over individual flags to
not build unnecessary targets of submodules.
=> Update libmotioncapture to include support for optitrack_closed_source

docs/installation.rst
When I don't specify the crazyswarm folder with the source, it gives pytest failed. After I sourced `../../../devel/setup.bash` it worked.
=> PyTest fail.

.github/workflows/ci-ros.yml, conda_env.yaml, docs/installation.rst, ros_ws/src/crazyswarm/scripts/test_videoOutput.py
Users who run the unit tests on their machine may be surprised to see the video output test fail (#584, #620).
Due to the difficulty of getting OpenGL output on CI, we were already skipping that test conditioned on the CI sentinel environment variables. It is more direct to simply skip it if the dependencies are not installed. This will fix the user failures.
Regarding the installation docs issue in #584, we move the visualizer dependencies into a separate step. This allows us to remove all visualizers from CI.
We still keep the visualizer dependencies in the conda environment because most users will want them, but we remove `ffmpeg` because video output does not seem like a popular feature.
=> clean up visualizer dependency CI/docs and video output test

docs/installation.rst
```python
conda create --name crazyswarm python=$CSW_PYTHON
```
is not a valid command, should be raw version number, like: 2.7 or 3.7 : )
=> Fix installation.rst instruction

ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyswarm_py.py
The `crazyflie.yaml` was read as a relative path in [crazyswarm_py.py](https://github.com/USC-ACTLab/crazyswarm/blob/master/ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyswarm_py.py), which depends on the workspace. We have to navigate to the [`scripts`](https://github.com/USC-ACTLab/crazyswarm/tree/master/ros_ws/src/crazyswarm/scripts) folder to execute the python scripts there. If we run these python scripts in other directories, the following error will occur:
`No such file or directory: '../launch/crazyflies.yaml'`
This is because of the following codes:
https://github.com/USC-ACTLab/crazyswarm/blob/ea4a67e57743fb7c8f56270edd96b191876f4057/ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyswarm_py.py#L39-L42
So I change the '../launch/crazyflies.yaml' in …
=> change absolute file path in pycrazyswarm

ros_ws/src/crazyswarm/scripts/pycrazyswarm/crazyswarm_py.py
Reverts USC-ACTLab/crazyswarm#716
As discussed in https://github.com/USC-ACTLab/crazyswarm/pull/716#issuecomment-1355336638, the change of the absolute path of "crazyflies.yaml" may conflict with the howto instructions in https://crazyswarm.readthedocs.io/en/latest/howto/howto.html#option-2-custom-ros-package. 
Sorry that I didn't notice this problem and thanks https://github.com/USC-ACTLab/crazyswarm/pull/716#issuecomment-1355336638 for pointing it out. I would recommend reverting this change to keep consistent with the instruction document.
=> Revert "change absolute file path in pycrazyswarm"
